// biome-ignore-all lint: This file is a mechanical JSX checkpoint generated from the verified Tailwind reference.
// biome-ignore-all format: Formatting generated JSX can change significant HTML whitespace.
import { SiteFooter, SiteHeader } from "../_components/site-chrome";

// Generated by scripts/react-migration/generate-reference-jsx.mjs.

const bodyClassName = "legacy-beaver-foundation bg-white text-[#303030] font-andada text-[16px] [font-weight:400] [line-height:1.6] not-italic m-[0] p-[0] wrap-break-word legacy-tablet:text-[14px] legacy-tablet:[line-height:1.45] wp-singular page-template-default page page-id-40 wp-theme-bb-theme wp-child-theme-bb-theme-child theme-bb-theme fl-builder fl-builder-2-10-1-6 fl-themer-1-5-2-4 fl-no-js fl-theme-builder-footer fl-theme-builder-footer-footer fl-theme-builder-header fl-theme-builder-header-header fl-framework-base fl-preset-default fl-full-width fl-search-active";

export function AboutTailwindReference() {
	return (
		<div className={bodyClassName} data-tailwind-migration-document="body" itemScope itemType="https://schema.org/WebPage">

<a aria-label="Skip to content" className="legacy-link absolute left-[-10000px] top-auto w-px h-px overflow-hidden p-[10px_15px] bg-white! focus:w-auto focus:h-auto focus:fixed focus:left-[0] focus:top-[0] focus:z-99999 fl-screen-reader-text" href="/tailwind-migration/about#fl-main-content">Skip to content</a><div className="relative [box-shadow:none] m-[0_auto] w-auto fl-page">
	<SiteHeader currentPage="about" />	<div id="fl-main-content" className="bg-white fl-page-content" itemProp="mainContentOfPage" role="main">


<div className="m-[0] p-[0] w-auto max-w-none legacy-before:table legacy-before:[content:'_'] legacy-after:table legacy-after:[content:'_'] legacy-after:clear-both fl-content-full container">
	<div className="m-[0] legacy-before:table legacy-before:[content:'_'] legacy-after:table legacy-after:[content:'_'] legacy-after:clear-both row">
		<div className="m-[0] p-[0] relative min-h-px legacy-desktop:float-left legacy-desktop:w-full fl-content col-md-12">
			<article className="mb-[40px] last:mb-[0] fl-post post-40 page type-page status-publish hentry" id="fl-post-40" itemScope itemType="https://schema.org/CreativeWork">

			<div className="legacy-before:table legacy-before:[content:'_'] legacy-after:table legacy-after:[content:'_'] legacy-after:clear-both fl-post-content clearfix" itemProp="text">
		<div className="fl-builder-content fl-builder-content-40 fl-builder-content-primary fl-builder-global-templates-locked" data-post-id="40"><div className="fl-row fl-row-full-width fl-row-bg-photo fl-node-5f1ff743a4bf8 fl-row-custom-height fl-row-align-bottom" data-node="5f1ff743a4bf8">
	<div className="bg-[url('/wp-content/uploads/2020/10/DFN-PageHero-Images-About3.jpg')] bg-no-repeat bg-center bg-scroll bg-cover min-h-[500px]! legacy-max-768:min-h-[400px]! mb-[10px]! legacy-max-768:mb-[0]! p-[0] fl-row-content-wrap">
						<div className="fl-row-content fl-row-full-width fl-node-content">

<div className="fl-col-group fl-node-5f1ff743a4bfd" data-node="5f1ff743a4bfd">
			<div className="w-full fl-col fl-node-5f1ff743a4bfe fl-col-bg-color" data-node="5f1ff743a4bfe">
	<div className="pb-[50px]! pl-[100px]! legacy-max-768:pl-[0]! fl-col-content fl-node-content"><div className="fl-module fl-module-heading fl-node-5f1ff82d217c6" data-node="5f1ff82d217c6">
	<div className="fl-module-content fl-node-content">
		<h1 className="font-vinyl text-[#333] [font-weight:100] uppercase not-italic text-[48px] [line-height:1.4] [letter-spacing:1px] legacy-tablet:[letter-spacing:0] fl-heading">
		<span className="text-white fl-heading-text">About DFN</span>
	</h1>
	</div>
</div>
</div>
</div>
	</div>
		</div>
	</div>
</div>
<div className="fl-row fl-row-full-width fl-row-bg-none fl-node-5f335c67c085d fl-row-default-height fl-row-align-center" data-node="5f335c67c085d">
	<div className="mt-[10px] mb-[10px] legacy-max-992:mt-[0] p-[60px_40px] legacy-max-768:p-[20px_0] fl-row-content-wrap">
						<div className="fl-row-content fl-row-fixed-width fl-node-content">

<div className="fl-col-group fl-node-5f335c67c08e1" data-node="5f335c67c08e1">
			<div className="w-full fl-col fl-node-5f335c67c08e2 fl-col-bg-color" data-node="5f335c67c08e2">
	<div className="fl-col-content fl-node-content"><div className="fl-module fl-module-heading fl-node-5f335c67c08e3" data-node="5f335c67c08e3">
	<div className="mb-[5px] fl-module-content fl-node-content">
		<h2 className="font-vinyl text-[#333] [font-weight:400] uppercase not-italic text-[32px] [line-height:1.2] [letter-spacing:1px] legacy-max-992:text-[24px] legacy-tablet:[letter-spacing:0] legacy-max-768:text-center fl-heading">
		<span className="fl-heading-text">About Dignity Freedom Network</span>
	</h2>
	</div>
</div>
<div className="fl-module fl-module-rich-text fl-node-5f335c67c08e4" data-node="5f335c67c08e4">
	<div className="mt-[5px] mb-[10px] legacy-max-768:mt-[0] fl-module-content fl-node-content">
		<div className="text-[18px] [line-height:1.8] legacy-max-992:text-[16px] legacy-max-992:[line-height:1.5] legacy-max-768:text-center fl-rich-text">
	<p className="m-[0_0_10px] p1">We are a group of Australians and New Zealanders caring for oppressed peoples in South Asia. We desire&nbsp;to see marginalised communities set free through education, healthcare and empowerment.</p>
<p className="text-center m-[0_0_10px] p1">Keep reading to learn more about how you can partner with us.</p>
</div>
	</div>
</div>
</div>
</div>
	</div>
		</div>
	</div>
</div>
<div className="fl-row fl-row-full-width fl-row-bg-color fl-node-5f200155d0eba fl-row-default-height fl-row-align-center" data-node="5f200155d0eba">
	<div className="bg-[#efefef] mt-[10px] mb-[10px] legacy-max-992:mt-[0] legacy-max-768:m-[5px_10px]! p-[60px_40px] legacy-max-768:p-[20px_0] fl-row-content-wrap">
						<div className="fl-row-content fl-row-fixed-width fl-node-content">

<div className="fl-col-group fl-node-5f200155d0fd7" data-node="5f200155d0fd7">
			<div className="w-full fl-col fl-node-5f200155d0fdb fl-col-bg-color" data-node="5f200155d0fdb">
	<div className="fl-col-content fl-node-content"><div className="fl-module fl-module-heading fl-node-5f2001ef3438f" data-node="5f2001ef3438f">
	<div className="mb-[5px] fl-module-content fl-node-content">
		<h2 className="font-vinyl text-[#333] [font-weight:400] uppercase not-italic text-[32px] [line-height:1.2] [letter-spacing:1px] legacy-max-992:text-[24px] legacy-tablet:[letter-spacing:0] text-center fl-heading">
		<span className="fl-heading-text">Our 5 main goals</span>
	</h2>
	</div>
</div>
<div className="fl-module fl-module-pp-advanced-tabs fl-node-5f200155d0fde" data-node="5f200155d0fde">
	<div className="fl-module-content fl-node-content">

<div className="legacy-about-tabs pp-tabs pp-tabs-horizontal pp-tabs-vertical-left pp-tabs-style-2 pp-clearfix">

	<div className="pp-tabs-labels pp-clearfix" role="tablist">
				<div id="pp-tab-5f200155d0fde-1" className="pp-tabs-label pp-tab-active pp-tab-icon-left" data-index="0" role="tab" tabIndex={-1} aria-selected="true" aria-controls="pp-tab-5f200155d0fde-1-content">
			<div className="pp-tab-label-inner">
				<div className="pp-tab-label-flex">

				<div className="pp-tab-title">Goal 1</div>

								</div>
							</div>
		</div>
				<div id="pp-tab-5f200155d0fde-2" className="pp-tabs-label pp-tab-icon-left" data-index="1" role="tab" tabIndex={-1} aria-selected="false" aria-controls="pp-tab-5f200155d0fde-2-content">
			<div className="pp-tab-label-inner">
				<div className="pp-tab-label-flex">

				<div className="pp-tab-title">Goal 2</div>

								</div>
							</div>
		</div>
				<div id="pp-tab-5f200155d0fde-3" className="pp-tabs-label pp-tab-icon-left" data-index="2" role="tab" tabIndex={-1} aria-selected="false" aria-controls="pp-tab-5f200155d0fde-3-content">
			<div className="pp-tab-label-inner">
				<div className="pp-tab-label-flex">

				<div className="pp-tab-title">Goal 3</div>

								</div>
							</div>
		</div>
				<div id="pp-tab-5f200155d0fde-4" className="pp-tabs-label pp-tab-icon-left" data-index="3" role="tab" tabIndex={-1} aria-selected="false" aria-controls="pp-tab-5f200155d0fde-4-content">
			<div className="pp-tab-label-inner">
				<div className="pp-tab-label-flex">

				<div className="pp-tab-title">Goal 4</div>

								</div>
							</div>
		</div>
				<div id="pp-tab-5f200155d0fde-5" className="pp-tabs-label pp-tab-icon-left" data-index="4" role="tab" tabIndex={-1} aria-selected="false" aria-controls="pp-tab-5f200155d0fde-5-content">
			<div className="pp-tab-label-inner">
				<div className="pp-tab-label-flex">

				<div className="pp-tab-title">Goal 5</div>

								</div>
							</div>
		</div>
			</div>

	<div className="pp-tabs-panels pp-clearfix">
				<div className="pp-tabs-panel">
			<div className="pp-tabs-label pp-tabs-panel-label pp-tab-active pp-tab-icon-left" data-index="0">
				<div className="pp-tab-label-inner">
					<div className="pp-tab-label-flex">
																									<div className="pp-tab-label-wrap">
							<div className="pp-tab-title">Goal 1</div>
																				</div>
					</div>

											<i className="pp-toggle-icon pp-tab-open fa fa-plus"></i>

											<i className="pp-toggle-icon pp-tab-close fa fa-minus"></i>
									</div>
			</div>
			<div id="pp-tab-5f200155d0fde-1-content" className="pp-tabs-panel-content pp-clearfix pp-tab-active" data-index="0" role="tabpanel" aria-labelledby="pp-tab-5f200155d0fde-1">
				<div itemProp="text"><p className="m-[0_0_10px]">See hope and dignity restored to marginalised women and girls through empowerment projects, economic development, health initiatives, community care and our anti human trafficking programme.</p>
</div>			</div>
		</div>
				<div className="pp-tabs-panel">
			<div className="pp-tabs-label pp-tabs-panel-label pp-tab-icon-left" data-index="1">
				<div className="pp-tab-label-inner">
					<div className="pp-tab-label-flex">
																									<div className="pp-tab-label-wrap">
							<div className="pp-tab-title">Goal 2</div>
																				</div>
					</div>

											<i className="pp-toggle-icon pp-tab-open fa fa-plus"></i>

											<i className="pp-toggle-icon pp-tab-close fa fa-minus"></i>
									</div>
			</div>
			<div id="pp-tab-5f200155d0fde-2-content" className="pp-tabs-panel-content pp-clearfix" data-index="1" role="tabpanel" aria-labelledby="pp-tab-5f200155d0fde-2">
				<div itemProp="text"><p className="m-[0_0_10px] p1"><span className="s1">Provide quality, English medium education to vulnerable children though our child sponsorship programme and raising funds for schools in rural and remote areas of South Asia, giving the students an opportunity to feel valued; to strengthen their self-esteem by teaching them their human worth and social equality and dignity.</span></p>
</div>			</div>
		</div>
				<div className="pp-tabs-panel">
			<div className="pp-tabs-label pp-tabs-panel-label pp-tab-icon-left" data-index="2">
				<div className="pp-tab-label-inner">
					<div className="pp-tab-label-flex">
																									<div className="pp-tab-label-wrap">
							<div className="pp-tab-title">Goal 3</div>
																				</div>
					</div>

											<i className="pp-toggle-icon pp-tab-open fa fa-plus"></i>

											<i className="pp-toggle-icon pp-tab-close fa fa-minus"></i>
									</div>
			</div>
			<div id="pp-tab-5f200155d0fde-3-content" className="pp-tabs-panel-content pp-clearfix" data-index="2" role="tabpanel" aria-labelledby="pp-tab-5f200155d0fde-3">
				<div itemProp="text"><p className="m-[0_0_10px]">Provide valuable job training and vocational skills centres, enabling poorer women and children to escape poverty and build a brighter future for their family.</p>
</div>			</div>
		</div>
				<div className="pp-tabs-panel">
			<div className="pp-tabs-label pp-tabs-panel-label pp-tab-icon-left" data-index="3">
				<div className="pp-tab-label-inner">
					<div className="pp-tab-label-flex">
																									<div className="pp-tab-label-wrap">
							<div className="pp-tab-title">Goal 4</div>
																				</div>
					</div>

											<i className="pp-toggle-icon pp-tab-open fa fa-plus"></i>

											<i className="pp-toggle-icon pp-tab-close fa fa-minus"></i>
									</div>
			</div>
			<div id="pp-tab-5f200155d0fde-4-content" className="pp-tabs-panel-content pp-clearfix" data-index="3" role="tabpanel" aria-labelledby="pp-tab-5f200155d0fde-4">
				<div itemProp="text"><p className="m-[0_0_10px] p1">Helping create and support healthier communities by developing health education and disease prevention programmes and through our health clinics.</p>
</div>			</div>
		</div>
				<div className="pp-tabs-panel">
			<div className="pp-tabs-label pp-tabs-panel-label pp-tab-icon-left" data-index="4">
				<div className="pp-tab-label-inner">
					<div className="pp-tab-label-flex">
																									<div className="pp-tab-label-wrap">
							<div className="pp-tab-title">Goal 5</div>
																				</div>
					</div>

											<i className="pp-toggle-icon pp-tab-open fa fa-plus"></i>

											<i className="pp-toggle-icon pp-tab-close fa fa-minus"></i>
									</div>
			</div>
			<div id="pp-tab-5f200155d0fde-5-content" className="pp-tabs-panel-content pp-clearfix" data-index="4" role="tabpanel" aria-labelledby="pp-tab-5f200155d0fde-5">
				<div itemProp="text"><p className="m-[0_0_10px] p1">Raise awareness of the needs and the opportunity to help vulnerable communities.</p>
</div>			</div>
		</div>
			</div>

</div>
	</div>
</div>
</div>
</div>
	</div>
		</div>
	</div>
</div>
<div className="fl-row fl-row-full-width fl-row-bg-none fl-node-5f1ff743a4c0a fl-row-default-height fl-row-align-center" data-node="5f1ff743a4c0a">
	<div className="mt-[10px] mb-[10px] legacy-max-992:mt-[0] legacy-max-768:m-[5px_10px]! p-[0] fl-row-content-wrap">
						<div className="fl-row-content fl-row-full-width fl-node-content">

<div className="fl-col-group fl-node-5f1ff743a4c0b fl-col-group-equal-height fl-col-group-align-center fl-col-group-custom-width" data-node="5f1ff743a4c0b">
			<div className="w-[40.99%] legacy-max-992:w-full! legacy-max-992:max-w-none! legacy-max-992:flex-initial! legacy-max-768:w-full! legacy-max-768:max-w-none! legacy-max-768:clear-none legacy-max-768:float-left fl-col fl-node-5f1ff743a4c0c fl-col-bg-photo fl-col-small fl-col-small-custom-width fl-visible-desktop fl-visible-large fl-visible-medium" data-node="5f1ff743a4c0c">
	<div className="bg-[url('/wp-content/uploads/2020/08/DFN-PageHero-Images-igd.jpg')] bg-no-repeat bg-center bg-scroll bg-cover fl-col-content fl-node-content"></div>
</div>
			<div className="w-[59.01%] legacy-max-992:w-full! legacy-max-992:max-w-none! legacy-max-992:flex-initial! legacy-max-768:w-full! legacy-max-768:max-w-none! legacy-max-768:clear-none legacy-max-768:float-left fl-col fl-node-5f1ff743a4c0e fl-col-bg-color fl-col-small-custom-width" data-node="5f1ff743a4c0e">
	<div className="p-[8%] fl-col-content fl-node-content"><div className="fl-module fl-module-heading fl-node-5f3dbf6c4669e" data-node="5f3dbf6c4669e">
	<div className="mb-[5px] fl-module-content fl-node-content">
		<h2 className="font-vinyl text-[#333] [font-weight:400] uppercase not-italic text-[32px] [line-height:1.2] [letter-spacing:1px] legacy-max-992:text-[24px] legacy-tablet:[letter-spacing:0] text-left legacy-max-768:text-center fl-heading">
		<span className="fl-heading-text">Why we do what we do</span>
	</h2>
	</div>
</div>
<div className="fl-module fl-module-rich-text fl-node-5f3dbf6b0877d" data-node="5f3dbf6b0877d">
	<div className="mt-[5px] mb-[10px] legacy-max-768:mt-[0] fl-module-content fl-node-content">
		<div className="text-[16px] [line-height:1.8] legacy-max-992:[line-height:1.5] legacy-max-768:text-center fl-rich-text">
	<p className="m-[0_0_10px] p1">Over the last 20 years our movement has responded to&nbsp;requests from community leaders to provide holistic English-medium education so&nbsp;marginalised children can discover dignity and freedom, affording them the opportunity to dream; and to provide freedom and restore dignity to at-risk girls and subjugated women.</p>
<p className="m-[0_0_10px] p1">We were asked to serve the poor, marginalised and outcastes. We&nbsp;focus on&nbsp;restoring the dignity and freedom of women and children who are the most vulnerable to&nbsp;exploitation and abuse.&nbsp;This is why we do what we do.</p>
</div>
	</div>
</div>
<div className="fl-module fl-module-heading fl-node-5f3dacf2600d9" data-node="5f3dacf2600d9">
	<div className="mb-[5px] fl-module-content fl-node-content">
		<h2 className="font-vinyl text-[#333] [font-weight:400] uppercase not-italic text-[32px] [line-height:1.2] [letter-spacing:1px] legacy-max-992:text-[24px] legacy-tablet:[letter-spacing:0] text-left legacy-max-768:text-center fl-heading">
		<span className="fl-heading-text">Where We Work</span>
	</h2>
	</div>
</div>
<div className="fl-module fl-module-rich-text fl-node-5f3dacfb1f33b" data-node="5f3dacfb1f33b">
	<div className="mt-[5px] mb-[10px] legacy-max-768:mt-[0] fl-module-content fl-node-content">
		<div className="text-[16px] [line-height:1.8] legacy-max-992:[line-height:1.5] legacy-max-768:text-center fl-rich-text">
	<p className="m-[0_0_10px] p2">We work wherever the needs are greatest as identified by the national leaders, serving them in their calling to address injustice.</p>
</div>
	</div>
</div>
</div>
</div>
	</div>
		</div>
	</div>
</div>
<div className="fl-row fl-row-full-width fl-row-bg-color fl-node-5f3dbdf37999c fl-row-default-height fl-row-align-center" data-node="5f3dbdf37999c">
	<div className="bg-[#efefef] mt-[10px] mb-[10px] legacy-max-992:mt-[0] legacy-max-768:m-[5px_10px]! p-[0] fl-row-content-wrap">
						<div className="fl-row-content fl-row-full-width fl-node-content">

<div className="fl-col-group fl-node-5f3dbdf379aa8 fl-col-group-equal-height fl-col-group-align-center fl-col-group-custom-width" data-node="5f3dbdf379aa8">
			<div className="w-full legacy-max-992:w-full! legacy-max-992:max-w-none! legacy-max-992:flex-initial! legacy-max-768:w-full! legacy-max-768:max-w-none! legacy-max-768:clear-none legacy-max-768:float-left fl-col fl-node-5f3dbdf379aaa fl-col-bg-color fl-col-small-custom-width" data-node="5f3dbdf379aaa">
	<div className="p-[8%] fl-col-content fl-node-content"><div className="fl-module fl-module-heading fl-node-5f3dbdf379aac" data-node="5f3dbdf379aac">
	<div className="mb-[5px] fl-module-content fl-node-content">
		<h2 className="font-vinyl text-[#333] [font-weight:400] uppercase not-italic text-[32px] [line-height:1.2] [letter-spacing:1px] legacy-max-992:text-[24px] legacy-tablet:[letter-spacing:0] text-left legacy-max-768:text-center fl-heading">
		<span className="fl-heading-text">Vulnerable People</span>
	</h2>
	</div>
</div>
<div className="fl-module fl-module-rich-text fl-node-5f3dbdf379aad" data-node="5f3dbdf379aad">
	<div className="mt-[5px] mb-[10px] legacy-max-768:mt-[0] fl-module-content fl-node-content">
		<div className="text-[16px] [line-height:1.8] legacy-max-992:[line-height:1.5] legacy-max-768:text-center fl-rich-text">
	<p className="m-[0_0_10px] p1">There are many marginalised and vulnerable communities in South Asia that need people to partner with them to break the poverty cycle.</p>
</div>
	</div>
</div>
</div>
</div>
	</div>
		</div>
	</div>
</div>
<div className="fl-row fl-row-full-width fl-row-bg-none fl-node-5f1ff743a4c08 fl-row-default-height fl-row-align-center" data-node="5f1ff743a4c08">
	<div className="mt-[10px] mb-[10px] legacy-max-992:mt-[0] p-[60px_40px] legacy-max-768:p-[20px_0] fl-row-content-wrap">
						<div className="min-w-[0] fl-row-content fl-row-fixed-width fl-node-content">

<div className="fl-col-group fl-node-5f1ffbee99189" data-node="5f1ffbee99189">
			<div className="w-full fl-col fl-node-5f1ffbee9922a fl-col-bg-color" data-node="5f1ffbee9922a">
	<div className="fl-col-content fl-node-content"><div className="fl-module fl-module-heading fl-node-5f2a7e408614a" data-node="5f2a7e408614a">
	<div className="mb-[5px] fl-module-content fl-node-content">
		<h2 className="font-vinyl text-[#333] [font-weight:400] uppercase not-italic text-[32px] [line-height:1.2] [letter-spacing:1px] legacy-max-992:text-[24px] legacy-tablet:[letter-spacing:0] text-center fl-heading">
		<span className="fl-heading-text">Our Mission</span>
	</h2>
	</div>
</div>
<div className="fl-module fl-module-rich-text fl-node-5f2a7e715bde6" data-node="5f2a7e715bde6">
	<div className="mt-[5px] mb-[10px] legacy-max-768:mt-[0] fl-module-content fl-node-content">
		<div className="text-[17px] [line-height:1.8] text-center legacy-max-992:text-[16px] legacy-max-992:[line-height:1.5] fl-rich-text">
	<p className="m-[0_0_10px] p1">Our mission is to restore hope and dignity to South Asia’s vulnerable people, particularly women and children. This is done by providing access to education, health care, advocacy, rehabilitation for victims of sexual slavery, community and economic development.</p>
</div>
	</div>
</div>
<div className="fl-module fl-module-separator fl-node-5f2a7eb2ac133" data-node="5f2a7eb2ac133">
	<div className="fl-module-content fl-node-content">
		<div className="[border-top-width:2px] max-w-[30%] m-auto border-t-[#efefef] [border-top-style:solid] fl-separator"></div>
	</div>
</div>
<div className="fl-module fl-module-heading fl-node-5f2a7eabb885a" data-node="5f2a7eabb885a">
	<div className="mb-[5px] fl-module-content fl-node-content">
		<h2 className="font-vinyl text-[#333] [font-weight:400] uppercase not-italic text-[32px] [line-height:1.2] [letter-spacing:1px] legacy-max-992:text-[24px] legacy-tablet:[letter-spacing:0] text-center fl-heading">
		<span className="fl-heading-text">Our Vision</span>
	</h2>
	</div>
</div>
<div className="fl-module fl-module-rich-text fl-node-5f2a7f2703720" data-node="5f2a7f2703720">
	<div className="mt-[5px] mb-[10px] legacy-max-768:mt-[0] fl-module-content fl-node-content">
		<div className="text-[17px] [line-height:1.8] text-center legacy-max-992:text-[16px] legacy-max-992:[line-height:1.5] fl-rich-text">
	<p className="m-[0_0_10px] p1">For South Asia’s oppressed and marginalised people to realise their human worth, dignity and gain self-reliance.</p>
</div>
	</div>
</div>
<div className="fl-module fl-module-separator fl-node-5f20bd107dc77" data-node="5f20bd107dc77">
	<div className="fl-module-content fl-node-content">
		<div className="[border-top-width:2px] max-w-[30%] m-auto border-t-[#efefef] [border-top-style:solid] fl-separator"></div>
	</div>
</div>
<div className="fl-module fl-module-heading fl-node-5f200155d0fdd" data-node="5f200155d0fdd">
	<div className="mb-[5px] fl-module-content fl-node-content">
		<h2 className="font-vinyl text-[#333] [font-weight:400] uppercase not-italic text-[32px] [line-height:1.2] [letter-spacing:1px] legacy-max-992:text-[24px] legacy-tablet:[letter-spacing:0] text-center fl-heading">
		<span className="fl-heading-text">Our Values</span>
	</h2>
	</div>
</div>
<div className="fl-module fl-module-rich-text fl-node-5f1ffbe12f7ce" data-node="5f1ffbe12f7ce">
	<div className="mt-[5px] mb-[10px] legacy-max-768:mt-[0] fl-module-content fl-node-content">
		<div className="text-[17px] [line-height:1.8] text-center legacy-max-992:text-[16px] legacy-max-992:[line-height:1.5] fl-rich-text">
	<p className="m-[0_0_10px]"><b>Dignity: </b>Believing all people have equal worth and intrinsic value, created in God’s image.<br />
<b>Prayer: </b>Underpinning all we do.<br />
<b>Integrity: </b>Doing what we say we will, transparently and accountably.<br />
<b>Communication: </b>Keeping all stakeholders informed.<br />
<b>Excellence: </b>Seeking constantly to improve.</p>
</div>
	</div>
</div>
</div>
</div>
	</div>
		</div>
	</div>
</div>
<div className="fl-row fl-row-full-width fl-row-bg-color fl-node-5f1ff743a4c12 fl-row-default-height fl-row-align-center" data-node="5f1ff743a4c12">
	<div className="bg-[#efefef] mt-[10px] mb-[10px] legacy-max-992:mt-[0] p-[0] legacy-max-768:p-[20px_0] fl-row-content-wrap">
						<div className="min-w-[0] fl-row-content fl-row-fixed-width fl-node-content">

<div className="fl-col-group fl-node-5f1ff743a4c13 fl-col-group-equal-height fl-col-group-align-center fl-col-group-custom-width" data-node="5f1ff743a4c13">
			<div className="w-[74.95%] legacy-max-992:w-[70%]! legacy-max-992:max-w-none! legacy-max-992:flex-initial! legacy-max-768:w-full! legacy-max-768:max-w-none! legacy-max-768:clear-none legacy-max-768:float-left fl-col fl-node-5f1ff743a4c15 fl-col-bg-color fl-col-small-custom-width" data-node="5f1ff743a4c15">
	<div className="p-[8%] fl-col-content fl-node-content"><div className="fl-module fl-module-heading fl-node-5f1ff743a4c16" data-node="5f1ff743a4c16">
	<div className="mb-[5px] fl-module-content fl-node-content">
		<h2 className="font-vinyl text-[#333] [font-weight:400] uppercase not-italic text-[32px] [line-height:1.2] [letter-spacing:1px] legacy-max-992:text-[24px] legacy-tablet:[letter-spacing:0] text-left legacy-max-768:text-center fl-heading">
		<span className="fl-heading-text">We Need your Support</span>
	</h2>
	</div>
</div>
<div className="fl-module fl-module-rich-text fl-node-5f1ff743a4c17" data-node="5f1ff743a4c17">
	<div className="mt-[5px] mb-[10px] legacy-max-768:mt-[0] fl-module-content fl-node-content">
		<div className="text-[18px] [line-height:1.5] legacy-max-992:text-[16px] legacy-max-768:text-center fl-rich-text">
	<p className="m-[0_0_10px] p1">These women and children have the odds stacked against them from birth, but education and empowerment can restore their dreams and hopes, bringing transformation not only to them but to their families and to entire communities.</p>
</div>
	</div>
</div>
</div>
</div>
			<div className="w-[25.05%] legacy-max-992:w-[30%]! legacy-max-992:max-w-none! legacy-max-992:flex-initial! legacy-max-768:w-full! legacy-max-768:max-w-none! legacy-max-768:clear-none legacy-max-768:float-left fl-col fl-node-5f1ff743a4c14 fl-col-bg-color fl-col-small fl-col-small-custom-width" data-node="5f1ff743a4c14">
	<div className="fl-col-content fl-node-content"><div className="fl-module fl-module-button fl-node-5f1ff743a4c1f" data-node="5f1ff743a4c1f">
	<div className="mt-[10px] fl-module-content fl-node-content">
		<div className="text-left legacy-max-768:text-center! fl-button-wrap fl-button-width-auto fl-button-left">
			<a href="https://dfn.org.au/donate/" target="_self" className="legacy-link legacy-about-cta fl-button">
							<span className="legacy-page-button-child:text-white legacy-page-button-child-hover:text-[#de6026] fl-button-text">Donate Now</span>
					</a>
</div>
	</div>
</div>
</div>
</div>
	</div>
		</div>
	</div>
</div>
</div>	</div>

</article>


		</div>
	</div>
</div>

	</div>
	<SiteFooter />	</div>




		</div>
	);
}
