// biome-ignore-all lint: This file is a mechanical JSX checkpoint generated from the verified Tailwind reference.
// biome-ignore-all format: Formatting generated JSX can change significant HTML whitespace.

import { HomeHero } from "../_components/home-hero";
import { HomeIntroduction } from "../_components/home-introduction";
import { FocusAreaSection } from "../_components/home-sections";
import { HomeSignup } from "../_components/home-signup";
import { SiteFooter, SiteHeader } from "../_components/site-chrome";

// Generated by scripts/react-migration/generate-reference-jsx.mjs.

const bodyClassName = "legacy-beaver-foundation bg-white text-[#303030] font-andada text-[16px] [font-weight:400] [line-height:1.6] not-italic m-[0] p-[0] wrap-break-word legacy-tablet:text-[14px] legacy-tablet:[line-height:1.45] home wp-singular page-template-default page page-id-18 page-parent wp-theme-bb-theme wp-child-theme-bb-theme-child theme-bb-theme fl-builder fl-builder-2-10-1-6 fl-themer-1-5-2-4 fl-no-js fl-theme-builder-footer fl-theme-builder-footer-footer fl-theme-builder-header fl-theme-builder-header-header fl-framework-base fl-preset-default fl-full-width fl-search-active";

export function HomeTailwindReference() {
	return (
		<div className={bodyClassName} data-tailwind-migration-document="body" itemScope itemType="https://schema.org/WebPage">

<a aria-label="Skip to content" className="legacy-link absolute left-[-10000px] top-auto w-px h-px overflow-hidden p-[10px_15px] bg-white! focus:w-auto focus:h-auto focus:fixed focus:left-[0] focus:top-[0] focus:z-99999 fl-screen-reader-text" href="/tailwind-migration#fl-main-content">Skip to content</a><div className="relative [box-shadow:none] m-[0_auto] w-auto fl-page">
	<SiteHeader currentPage="home" />	<div id="fl-main-content" className="bg-white fl-page-content" itemProp="mainContentOfPage" role="main">


<div className="m-[0] p-[0] w-auto max-w-none legacy-before:table legacy-before:[content:'_'] legacy-after:table legacy-after:[content:'_'] legacy-after:clear-both fl-content-full container">
	<div className="m-[0] legacy-before:table legacy-before:[content:'_'] legacy-after:table legacy-after:[content:'_'] legacy-after:clear-both row">
		<div className="m-[0] p-[0] relative min-h-px legacy-desktop:float-left legacy-desktop:w-full fl-content col-md-12">
			<article className="mb-[40px] last:mb-[0] fl-post post-18 page type-page status-publish hentry" id="fl-post-18" itemScope itemType="https://schema.org/CreativeWork">

			<div className="legacy-before:table legacy-before:[content:'_'] legacy-after:table legacy-after:[content:'_'] legacy-after:clear-both fl-post-content clearfix" itemProp="text">
		<div className="fl-builder-content fl-builder-content-18 fl-builder-content-primary fl-builder-global-templates-locked" data-post-id="18"><HomeHero />
<HomeIntroduction />
<FocusAreaSection
	ctaLabel="Education"
	description="Opens doors and opportunities. Education empowers children and gives them a reason to dream. Our schools provide quality, English-medium education to children from poor and marginalised communities including health care, sports and the Arts; emphasising respect for others, self-worth, dignity, freedom and equality."
	href="https://dfn.org.au/education/"
	image={{ alt: "DFN-HomepageHeroImages-KidsClass-landscape-resized", src: "/tailwind-migration/reference/wp-content/uploads/bb-plugin/cache/DFN-HomepageHeroImages-KidsClass-landscape-resized-landscape-ded82d0737bfa22840482d215ee09a8a-5f1a30ba14b55.jpg", title: "DFN-HomepageHeroImages-KidsClass-landscape-resized" }}
	layout="image-left"
	startsFlush
	title="Education"
/>
<FocusAreaSection
	ctaLabel="Healthcare"
	description="Healthcare is essential to break the poverty cycle. Community Health Workers, primary clinics and HIV/AIDS centres help prevent sickness and disease – a cause and consequence of poverty and inequality. Currently our focus is mitigating the impact of COVID-19."
	href="https://dfn.org.au/give/healthcare/"
	image={{ alt: "Health-Workers-2-web-resized", src: "/tailwind-migration/reference/wp-content/uploads/bb-plugin/cache/Health-Workers-2-web-resized-landscape-8d7c8d75f5aa5b877a975a71e0d63469-5f1a24324944c.jpg", title: "Health-Workers-2-web-resized" }}
	layout="image-right"
	title="Healthcare"
/>
<FocusAreaSection
	ctaLabel="ECONOMIC EMPOWERMENT"
	description="Economic Empowerment restores the potential for earned dignity. Business start-up grants, self-help groups and vocational training enable the poor and vulnerable to earn a livelihood, become self-sufficient and hold their heads up high."
	href="https://dfn.org.au/give/economic-empowerment/"
	image={{ alt: "EconomicEmpower-resized", src: "/tailwind-migration/reference/wp-content/uploads/bb-plugin/cache/EconomicEmpower-resized-landscape-72dbc3c7dab2c48fa69b2e82a9742faf-5f1a414f13050.jpg", title: "EconomicEmpower-resized" }}
	layout="image-left-mobile-first"
	title="ECONOMIC EMPOWERMENT"
/>
<FocusAreaSection
	ctaLabel="Vulnerable women and girls"
	description="Prevention and awareness programmes among at-risk women and girls and their local community. Our teams protect vulnerable girls wherever possible and rescue abused women and girls. We provide these empower these women and girls to find a new future with health, dignity and hope."
	href="https://dfn.org.au/anti-human-trafficking/"
	image={{ alt: "IMG_6118resized", src: "/tailwind-migration/reference/wp-content/uploads/bb-plugin/cache/IMG_6118resized-landscape-52579888afcf441cd45e06a5eae7cee9-5f8e4586499aa.jpg", title: "IMG_6118resized" }}
	layout="image-right"
	title="Vulnerable women and girls"
/>
<HomeSignup />
</div>	</div>

</article>


		</div>
	</div>
</div>

	</div>
	<SiteFooter />	</div>




		</div>
	);
}
